
resource "stackpoint_cluster" "my-cluster" {
	org_id = "111",
        cluster_name = "Test DO Cluster TerraForm",
        provider_name = "do",
        provider_key = "3556",
        master_count = "1",
        master_size = "2gb",
        worker_count = "2",
        worker_size = "2gb",
        region = "nyc1",
        k8s_version = "v1.8.3",
        rbac_enabled = true,
        dashboard_enabled = true,
        etcd_type = "self_hosted",
        platform = "coreos",
        channel = "stable",
        ssh_keyset = "3524",
	solutions = [""],
}
